### ISSUE TITLE
Task Tracking Stats: Swap Between Player / Ship

### ISSUE THREAD

**Issue by lunarcloud** [lunarcloud/sta-play-webapp#15]
Should have a toggle to swap between player and ship (it would be assisting) stats.
Despite not being simultaneously visible, they should both be saved & loaded.
So, if the toggle is set to ship, then it shows the ship Systems and Departments.
If the toggle is set to player (default), then it shows the player Attributes and Disciplines/Departments.

- [x] Add toggle slider that swaps viewing player or ship stats, to the tracker widget
- [x] Add player and ship icons to the appropriate sides of the toggle slider
- [x] Save/Load the additional "ship-system" & "ship-department" values in the trackers db

### Current
|   |   |
|--|--|
| Stats | [Control] |
|          | [Command] |
#### Player
|   |   |
|--|--|
| Stats | [Control] |
|  P (O--) S   | [Command] |

#### Ship
|   |   |
|--|--|
| Stats | [Engines] |
|  P (--O) S   | [Command] |

**Comment by lunarcloud** [comment]
![image](https://github.com/lunarcloud/sta-play-webapp/assets/1565970/f1b5ed5e-165a-4da3-9891-fd1407761316)
